---
- name: Install apache
  hosts:  ubuntu
  tasks:
    - name: install apache
      apt:
        name: apache2
        state:  latest

    - name: start the service
      service:
        name: apache2
        state:  started
        enabled: true

    - name: allow the service from firewall
      ufw:
        rule:  allow
        port: '80'
        proto:  tcp
        state:  enabled
      notify: restart ufw

    - name: copy index file
      copy:
        src:  ./index.html
        dest: /var/www/html
      notify: restart apache2

  handlers:
    - name: restart ufw
      service:
        name: ufw
        state:  restarted

    - name: restart apache2
      service:
        name: apache2
        state:  restarted
